export const USER_LOADING = "USER_LOADING";
export const USER_LOADED = "USER_LOADED";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";

export const GET_ERRORS = "GET_ERRORS";
export const CREATE_MESSAGE = "CREATE_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";

export const RECIPE_LOADING = "RECIPE_LOADING";
export const GET_RECIPES = "GET_RECIPES";
export const GET_DETAIL_RECIPE = "GET_DETAIL_RECIPE";
export const CLEAR_RECIPE = "CLEAR_RECIPE";
export const GET_ALL_RECIPES = "GET_ALL_RECIPES";
export const GET_USER_RECIPES = "GET_USER_RECIPES";
export const CREATE_RECIPE = "CREATE_RECIPE";
export const EDIT_RECIPE = "EDIT_RECIPE";
export const DELETE_RECIPE = "DELETE_RECIPE";
export const LIKE_RECIPE = "LIKE_RECIPE";
export const SAVE_RECIPE = "SAVE_RECIPE";

export const ADD_INGREDIENTS = "ADD_INGREDIENTS";
export const ADD_PROCEDURES = "ADD_PROCEDURES";
export const ADD_COOKTIME = "ADD_COOKTIME";
export const ADD_CATEGORY = "ADD_CATEGORY";
export const ADD_PICTURE = "ADD_PICTURE";
